export const MESSAGE_TYPE = {
  OPEN_BROWSER: 'OPEN_BROWSER',
  OPEN_OUTSIDE_BROWSER: 'OPEN_OUTSIDE_BROWSER',
  LOGIN_DATA: 'LOGIN_DATA',
  LOGOUT: 'LOGOUT',
  DONE_ADD_EVENT_MESSAGE: 'DONE_ADD_EVENT_ON_MESSAGE',
  FIREBASE_MESSAGE: 'FIREBASE_MESSAGE',
};
