export const COMMON_PERMISSIONS = {
  SITE_OWNER: 'SITE_OWNER',
  SUPPER_ADMIN: 'SUPPER_ADMIN',
  ADMIN: 'ADMIN',
  ADMIN_USER: 'ADMIN_USER',
  SITE_USER: 'SITE_USER',
  VIEW_CRM: 'VIEW_CRM',
  EDIT_REFERRER: 'EDIT_REFERRER',
  DOWNLOAD: 'DOWNLOAD',
  DOWNLOAD_ADVANCED: 'DOWNLOAD_ADVANCED',
};

export const ADMIN_AND_SUPER_ADMIN_PERMISSIONS = [
  COMMON_PERMISSIONS.SITE_OWNER,
  COMMON_PERMISSIONS.ADMIN,
  COMMON_PERMISSIONS.SUPPER_ADMIN,
  COMMON_PERMISSIONS.ADMIN_USER,
];
