import {
  useDetailForm,
  useDocumentDetail,
  useDocumentDetailVisibility,
  useItem,
  useItemDocument,
  useItemVisibility,
  useOnCloseDocumentDetail,
  useSetDocumentDetailVisibility,
  useSetItem,
  useSetItems,
  useSetItemVisibility,
  useSubmitAndContinueDocumentButtonRef,
  useSubmitDocumentButtonRef,
} from './document-detail-hooks';
import {
  useApiEndpoint,
  useDocumentIdName,
  useFeature,
  useFeatureId,
  useSelectFeatureData,
} from './feature-hooks';
import {
  useCreateButtonRef,
  useHandleClickOnCreateDocumentButton,
  useSearchForm,
  useSubmitSearchForm,
} from './search-form-hooks';
import {
  useSetDocumentDetail,
  useEditDocumentControl,
  useDeleteDocumentControl,
  usePagination,
  useIsLoadingData,
  useTableSourceData,
  useEditDocumentSelected,
  useClearDocumentDetail,
} from './table-hooks';
export * from './common';

export {
  useDetailForm,
  useSearchForm,
  useSubmitSearchForm,
  useSetDocumentDetail,
  useFeature,
  useFeatureId,
  useApiEndpoint,
  useDocumentDetailVisibility,
  useSetDocumentDetailVisibility,
  useDocumentDetail,
  useDocumentIdName,
  useCreateButtonRef,
  useOnCloseDocumentDetail,
  useSubmitDocumentButtonRef,
  useSubmitAndContinueDocumentButtonRef,
  useHandleClickOnCreateDocumentButton,
  useEditDocumentControl,
  useDeleteDocumentControl,
  usePagination,
  useIsLoadingData,
  useTableSourceData,
  useSelectFeatureData,
  useEditDocumentSelected,
  useSetItems,
  useSetItem,
  useSetItemVisibility,
  useItem,
  useItemDocument,
  useItemVisibility,
  useClearDocumentDetail,
};
