import { ACTION_CODES } from '../../components/features/fina/progress-template/utils';

export const TASK_PRIORITY = {
  LOW: 1,
  NORMAL: 2,
  HIGH: 3,
  ASAP: 4,
};

export const TASK_CLASSIFICATION_FORM = {
  CREDIT: 1,
  INSURANCE: 2,
  INVEST: 3,
  REAL_ESTATE: 4,
};

export const TASK_STATUSES = {
  NEW: 'new',
  PROCESSING: 'processing',
  CANCEL: 'cancel',
  DONE: 'done',
  DELETED: 'deleted',
  CREATED: 'created',
  ASSIGNED: 'assigned',
  CONSULTED: 'consulted',
  WAITED: 'waited',
  CONFIRMED: 'confirmed',
  CLOSED: 'closed',
};

export const TASK_STATUSES_ASSIGNED = {
  NOT_PROCESSING: 'not_processing', // chưa xủ lý
  PROCESSING: 'processing', // đang xử lý
  WAITING_FOR_BANK_APPROVAL: 'waiting_for_bank_approval', // chờ ngân hàng phản hồi,
  WAITING_FOR_BANK_PROCESS: 'waiting_for_bank_process', // chờ ngân hàng xử lý,
  BANK_APPROVAL: 'received', // ngân hàng phê duyệt,
  BANK_REJECT: 'reject',
  WAITING_FOR_STAFF_FINA: 'waiting_for_staff_fina',
  CREATE_PROFILE:'create_profile',
  OVERDUE_FOR_BANK_RESPONSE: 'overdue_for_bank_response',
};

export const TASK_PRIORITY_LABEL_MAPPING = {
  [TASK_PRIORITY.LOW]: 'CRM_TASK_PRIORITY_LOW',
  [TASK_PRIORITY.NORMAL]: 'CRM_TASK_PRIORITY_NORMAL',
  [TASK_PRIORITY.HIGH]: 'CRM_TASK_PRIORITY_HIGH',
  [TASK_PRIORITY.ASAP]: 'CRM_TASK_PRIORITY_ASAP',
};

export const TASK_PRIORITY_COLOR_MAPPING = {
  [TASK_PRIORITY.LOW]: 'orange',
  [TASK_PRIORITY.NORMAL]: 'volcano',
  [TASK_PRIORITY.HIGH]: 'red',
  [TASK_PRIORITY.ASAP]: 'magenta',
};

export const TASK_TYPES = {
  CALL: 'call',
  COUNSELLING: 'counselling',
  DEAL_PROCESSING_TASK: 'deal_processing_task',
  WANT_TO_BUY: 'WANT_TO_BUY',
  INTRODUCE_BUYER: 'INTRODUCE_BUYER',
  CLAIM_INSURANCE: 'claim_insurance',
  INSURANCE: 'INSURANCE',
  REAL_ESTATE: 'REAL_ESTATE',
  BOND: 'BOND',
  FUND: 'FUND',
  FINANCIAL_PLANNING: 'FINANCIAL_PLANNING',
  OTHER: 'other',
};

export const TASK_TYPES_LABEL_MAPPING = {
  [TASK_TYPES.CALL]: 'CRM_TASK_TYPE_CALL',
  [TASK_TYPES.COUNSELLING]: 'CRM_TASK_TYPE_COUNSELLING',
  [TASK_TYPES.DEAL_PROCESSING_TASK]: 'CRM_TASK_TYPE_DEAL_PROCESSING_TASK',
  [TASK_TYPES.WANT_TO_BUY]: 'WANT_TO_BUY',
  [TASK_TYPES.INTRODUCE_BUYER]: 'INTRODUCE_BUYER',
};

export const TASK_TYPES_COLOR_MAPPING = {
  [TASK_TYPES.CALL]: 'blue',
  [TASK_TYPES.COUNSELLING]: 'geekblue',
  [TASK_TYPES.DEAL_PROCESSING_TASK]: 'purple',
  [TASK_TYPES.WANT_TO_BUY]: 'lime',
  [TASK_TYPES.INTRODUCE_BUYER]: 'green',
};

export const TASK_STATUSES_LABEL_MAPPING = {
  [TASK_STATUSES.NEW]: 'CRM_TASK_STATUS_NEW',
  [TASK_STATUSES.PROCESSING]: 'CRM_TASK_STATUS_PROCESSING',
  [TASK_STATUSES.CANCEL]: 'CRM_TASK_STATUS_CANCEL',
  [TASK_STATUSES.DONE]: 'CRM_TASK_STATUS_DONE',
  [TASK_STATUSES.CREATED]: 'CRM_TASK_STATUS_RECORD',
  [TASK_STATUSES.ASSIGNED]: 'CRM_TASK_STATUS_RECORD',

  [ACTION_CODES.ACTION_NOT_START]: 'CRM_TASK_STATUS_NOT_STARTED',
  [ACTION_CODES.ACTION_STARTED]: 'CRM_TASK_STATUS_STARTED',
  [ACTION_CODES.ACTION_PROGRESS_50_PERCENT]: 'CRM_TASK_STATUS_PROCESSING',
  [ACTION_CODES.ACTION_DONE]: 'CRM_TASK_STATUS_DONE',
  [TASK_STATUSES.CONSULTED]: 'CRM_TASK_STATUS_CONSULTED',
};

export const TASK_STATUSES_COLOR_MAPPING = {
  [TASK_STATUSES.NEW]: 'green',
  [TASK_STATUSES.PROCESSING]: 'cyan',
  [TASK_STATUSES.CANCEL]: 'red',
  [TASK_STATUSES.DONE]: '#108ee9',
  [TASK_STATUSES.CREATED]: 'blue',
  [TASK_STATUSES.ASSIGNED]: 'orange',

  [ACTION_CODES.ACTION_NOT_START]: 'lime',
  [ACTION_CODES.ACTION_STARTED]: 'geekblue',
  [ACTION_CODES.ACTION_PROGRESS_50_PERCENT]: 'purple',
  [ACTION_CODES.ACTION_DONE]: '#108ee9',
  [TASK_STATUSES.CONSULTED]: 'green',
  [TASK_STATUSES.WAITED]: 'orange',
  [TASK_STATUSES.CLOSED]: 'red',
  [TASK_STATUSES.CONFIRMED]: 'green',
};

export const TASK_SOURCE = {
  MYSELF: 'myself',
  OTHERS: 'others',
};

export const CODE_QUERY_INFO = [
  'QUESTION_LA_INCOME',
  'QUESTION_LA_COST_PER_MONTH',
  'QUESTION_LA_REAL_INTEREST_RATE',
  'QUESTION_LA_BORROWED_TIME',
  'QUESTION_LPC_LOAN_DEMAND',
  'QUESTION_LPC_LOAN_PLAN',
  'QUESTION_LPC_INCOME',
  'QUESTION_LPC_ACCUMULATED_ASSETS',
  'QUESTION_LPC_REPAYMENT_PERIOD',
  'QUESTION_LPC_EVALUATE_PLAN',
  'QUESTION_LPC_EVALUATE_SOURCE_OF_INCOME',
  'QUESTION_LPC_EVALUATE_CREDIT_HISTORY',
  'QUESTION_LPC_EVALUATE_BORROWING_AGE_AND_PROPERTY_OWNER_AGE',
];

export enum CODE_QUERY_INFO_DATA  {
  QUESTION_LA_INCOME= 'QUESTION_LA_INCOME',
  QUESTION_LA_COST_PER_MONTH= 'QUESTION_LA_COST_PER_MONTH',
  QUESTION_LA_REAL_INTEREST_RATE = 'QUESTION_LA_REAL_INTEREST_RATE',
  QUESTION_LA_BORROWED_TIME = 'QUESTION_LA_BORROWED_TIME',
  QUESTION_LPC_LOAN_DEMAND = 'QUESTION_LPC_LOAN_DEMAND',
  QUESTION_LPC_LOAN_PLAN = 'QUESTION_LPC_LOAN_PLAN',
  QUESTION_LPC_INCOME = 'QUESTION_LPC_INCOME',
  QUESTION_LPC_ACCUMULATED_ASSETS = 'QUESTION_LPC_ACCUMULATED_ASSETS',
  QUESTION_LPC_REPAYMENT_PERIOD = 'QUESTION_LPC_REPAYMENT_PERIOD',
  QUESTION_LPC_EVALUATE_PLAN = 'QUESTION_LPC_EVALUATE_PLAN',
  QUESTION_LPC_EVALUATE_SOURCE_OF_INCOME = 'QUESTION_LPC_EVALUATE_SOURCE_OF_INCOME',
  QUESTION_LPC_EVALUATE_CREDIT_HISTORY = 'QUESTION_LPC_EVALUATE_CREDIT_HISTORY',
  QUESTION_LPC_EVALUATE_BORROWING_AGE_AND_PROPERTY_OWNER_AGE ='QUESTION_LPC_EVALUATE_BORROWING_AGE_AND_PROPERTY_OWNER_AGE',
}

export const CODE_QUERY_INFO_VIEW_LABEL_MAPPING = {
  [CODE_QUERY_INFO_DATA.QUESTION_LA_INCOME]: 'Thu nhập (sau thuế) hàng tháng',
  [CODE_QUERY_INFO_DATA.QUESTION_LA_COST_PER_MONTH]: 'Chi phí ước tính hàng tháng',
  [CODE_QUERY_INFO_DATA.QUESTION_LA_REAL_INTEREST_RATE]: 'Lãi suất thực mong muốn (hàng năm)',
  [CODE_QUERY_INFO_DATA.QUESTION_LA_BORROWED_TIME]: 'Thời gian vay mong muốn của khoản vay (năm)',
  [CODE_QUERY_INFO_DATA.QUESTION_LPC_LOAN_DEMAND]: 'Nhu cầu vay',
  [CODE_QUERY_INFO_DATA.QUESTION_LPC_LOAN_PLAN]: 'Phương án vay',
  [CODE_QUERY_INFO_DATA.QUESTION_LPC_INCOME]: 'Nguồn thu',
  [CODE_QUERY_INFO_DATA.QUESTION_LPC_ACCUMULATED_ASSETS]: 'Tài sản tích lũy',
  [CODE_QUERY_INFO_DATA.QUESTION_LPC_REPAYMENT_PERIOD]: 'Thời gian vay và trả nợ dự kiến',
  [CODE_QUERY_INFO_DATA.QUESTION_LPC_EVALUATE_PLAN]: 'Phương án',
  [CODE_QUERY_INFO_DATA.QUESTION_LPC_EVALUATE_SOURCE_OF_INCOME]: 'Nguồn thu',
  [CODE_QUERY_INFO_DATA.QUESTION_LPC_EVALUATE_CREDIT_HISTORY]: 'Lịch sử tín dụng',
  [CODE_QUERY_INFO_DATA.QUESTION_LPC_EVALUATE_BORROWING_AGE_AND_PROPERTY_OWNER_AGE]: 'Độ tuổi vay vốn và độ tuổi chủ tài sản',
};

export const CODE_QUERY_NOTE = [
  'QUESTION_LPC_CREDIT_HISTORY',
  'QUESTION_LPC_EVALUATE_MORTAGE_TYPE',
];

export enum CODE_QUERY_NOTE_DATA  {
  QUESTION_LPC_CREDIT_HISTORY= 'QUESTION_LPC_CREDIT_HISTORY',
  QUESTION_LPC_EVALUATE_MORTAGE_TYPE= 'QUESTION_LPC_EVALUATE_MORTAGE_TYPE',
}

export const CODE_QUERY_NOTE_VIEW_LABEL_MAPPING = {
  [CODE_QUERY_NOTE_DATA.QUESTION_LPC_CREDIT_HISTORY]: 'Lịch sử tín dụng',
  [CODE_QUERY_NOTE_DATA.QUESTION_LPC_EVALUATE_MORTAGE_TYPE]: 'Loại hình tài sản thế chấp (đặc điểm, cấu trúc)',
};

export enum TASK_RESPONSE_STATUS{
  WAITING_TO_RECEIVE = 'waiting_to_receive',
  RECEIVED = 'received',
  REJECT = 'reject',
  RESPONDED= 'responded',
  ENOUGH_PEOPLE_TO_ACCEPT = 'enough_people_to_accept'
}

export const TASK_RESPONSE_STATUS_OPTIONS = [
  {
    label: 'Chờ tiếp nhận',
    value: TASK_RESPONSE_STATUS.WAITING_TO_RECEIVE,
  },
  {
    label: 'Tiếp nhận',
    value: TASK_RESPONSE_STATUS.RECEIVED,
  },
  {
    label: 'Từ chối',
    value: TASK_RESPONSE_STATUS.REJECT,
  },
  {
    label: 'Đã phản hồi nội dung',
    value: TASK_RESPONSE_STATUS.RESPONDED,
  },
  {
    label: 'Đã đủ người tiếp nhận',
    value: TASK_RESPONSE_STATUS.ENOUGH_PEOPLE_TO_ACCEPT,
  },
];

export const TASK_RESPONSE_STATUS_COLOR_MAPPING = {
  [TASK_RESPONSE_STATUS.WAITING_TO_RECEIVE]: 'green',
  [TASK_RESPONSE_STATUS.RECEIVED]: 'blue',
  [TASK_RESPONSE_STATUS.REJECT]: 'red',
  [TASK_RESPONSE_STATUS.ENOUGH_PEOPLE_TO_ACCEPT]: 'yellow',
  [TASK_RESPONSE_STATUS.RESPONDED]: 'lime',
};

export const ROOT_TASK = {
  WEB: 'Website',
  MOBILE: 'Mobile App',
  IHOUZZ: 'Ihouzz',
  CHO_TOT: 'Chợ tốt',
  STAFF: 'Nhân viên',
  LANDING_PAGE: 'Landing page',
  POS: 'POS',
  FIDT: 'FIDT', // change text to Fina Wealthmanagement
};

export const FIDT_TASK_TYPE_DISPLAY = 'Fina Wealthmanagement';

export const ROOT_TASK_OPTIONS = Object.values(ROOT_TASK).map(item => {
  if (item === ROOT_TASK.FIDT) {
    return {
      value: ROOT_TASK.FIDT,
      label: FIDT_TASK_TYPE_DISPLAY,
    };
  }
  return { value: item, label: item };
});

export const MAPPING_ROOT_TEXT = {
  [ROOT_TASK.WEB]: ROOT_TASK.WEB,
  [ROOT_TASK.MOBILE]: ROOT_TASK.MOBILE,
  [ROOT_TASK.IHOUZZ]: ROOT_TASK.IHOUZZ,
  [ROOT_TASK.CHO_TOT]: ROOT_TASK.CHO_TOT,
  [ROOT_TASK.STAFF]: ROOT_TASK.STAFF,
  [ROOT_TASK.LANDING_PAGE]: ROOT_TASK.LANDING_PAGE,
  [ROOT_TASK.POS]: ROOT_TASK.POS,
  [ROOT_TASK.FIDT]: FIDT_TASK_TYPE_DISPLAY,
};

export const TASK_ACTIVE_KEY_TABS = {
  TASK_INFORMATION: 'detail',
  CALL_LOG: 'callLog',
  SURVEY_QUESTION: 'question',
  FEEDBACK: 'feedback',
  TASK_ASSIGN: 'task_assign',
};

export const TASK_RESPONSE_STATUS_LABEL_MAPPING = {
  [TASK_RESPONSE_STATUS.WAITING_TO_RECEIVE]: 'Chờ tiếp nhận',
  [TASK_RESPONSE_STATUS.RECEIVED]: 'Đã phản hồi',
  [TASK_RESPONSE_STATUS.REJECT]: 'Đã từ chối',
  [TASK_RESPONSE_STATUS.ENOUGH_PEOPLE_TO_ACCEPT]: 'Đã đủ người tiếp nhận',
};

export const RESPONSE_STATUS_SEEN_BY_FINA_STAFF = {
  RECEIVED: 'received',
  REJECT: 'reject',
  RESPONDED: 'responded',
};

export const RESPONSE_STATUS_SEEN_BY_FINA_STAFF_COLOR_MAPPING = {
  [RESPONSE_STATUS_SEEN_BY_FINA_STAFF.RECEIVED]: 'blue',
  [RESPONSE_STATUS_SEEN_BY_FINA_STAFF.REJECT]: 'red',
  [RESPONSE_STATUS_SEEN_BY_FINA_STAFF.RESPONDED]: 'green',
};

export const RESPONSE_STATUS_SEEN_BY_FINA_STAFF_LABEL_MAPPING = {
  [RESPONSE_STATUS_SEEN_BY_FINA_STAFF.RECEIVED]: 'Đã tiếp nhận',
  [RESPONSE_STATUS_SEEN_BY_FINA_STAFF.REJECT]: 'Từ chối',
  [RESPONSE_STATUS_SEEN_BY_FINA_STAFF.RESPONDED]: 'Đã phản hồi nội dung',
};

export const ADMIN_PERMISSIONS: any = {
  SITE_OWNER: 'SITE_OWNER',
  SUPPER_ADMIN: 'SUPPER_ADMIN',
  ADMIN: 'ADMIN',
  SITE_USER: 'SITE_USER',
};

export const ROLES_CODE = {
  FINA_ADMIN: 'ADMIN',
  FINA_STAFF: 'FINA_STAFF',
  BANK_STAFF: 'BANK_STAFF',
  BANK_ADMIN: 'ADMIN_BANK',
  REAL_ESTATE_STAFF: 'REAL_ESTATE_STAFF',
  INSURANCE_STAFF: 'INSURANCE_STAFF',
  COLLABORATOR: 'COLLABORATOR',
  CUSTOMER: 'CUSTOMER',
  SALE_BDS: 'SALE_BDS',
};
