
export interface Answer {
  content?: string;
  hint?: string;
  isCorrect?: boolean;
  audio?: {
    url?: string;
    playStartAt?: number;
    playEndAt?: number;
    duration?: number;
  };
  image?: {
    url?: string;
    width?: number;
    height?: number;
  };
  color?: string;
}

export const DISPLAY_MODES = {
  ROW: 'row',
  NEXT_TO: 'next_to',
};

export const MEDIA_DISPLAY_MODES = {
  MEDIA_IN_FRONT: 'media_in_front',
  MEDIA_ABOVE: 'media_above',
  MEDIA_BELOW: 'media_below',
  MEDIA_IN_THE_BACK: 'media_in_the_back',
  MEDIA_BELOW_TEXT: 'media_below_text',
};

export const MEDIA_DISPLAY_MODES_MAP_CLASSNAME = {
  [MEDIA_DISPLAY_MODES.MEDIA_IN_FRONT]: 'media-in-front',
  [MEDIA_DISPLAY_MODES.MEDIA_ABOVE]: 'media-above',
  [MEDIA_DISPLAY_MODES.MEDIA_BELOW]: 'media-below',
  [MEDIA_DISPLAY_MODES.MEDIA_IN_THE_BACK]: 'media-in-the-back',
  [MEDIA_DISPLAY_MODES.MEDIA_BELOW_TEXT]: 'media-below-text',
};

export const MEDIA_RATIO = {
  '1:1': '1:1',
  '4:3': '4:3',
  '16:9': '16:9',
};

export const MEDIA_RATIO_MAP_TO_VALUE = {
  [MEDIA_RATIO['1:1']]: 1,
  [MEDIA_RATIO['4:3']]: 4 / 3,
  [MEDIA_RATIO['16:9']]: 16 / 9,
};

export const QUESTION_SELECTION_MODE = {
  MULTIPLE: 'multiple',
  SINGLE: 'single',
};

export interface Question {
  type?: string | any;
  mode?: 'single' | 'multiple';
  content?: string;
  answers?: Answer[];
  displayMode?: 'row' | 'next_to';
  mediaDisplayMode?:
  | 'media_in_front'
  | 'media_above'
  | 'media_below'
  | 'media_in_the_back'
  | 'media_below_text';
  mediaRatio?: '1:1' | '4:3' | '16:9';
  direction?: 'next-to' | 'row';
  selectionMode?: 'multiple' | 'single';
  suffix?: string;
  required?: boolean;
  description?: string;
}

export interface QuestionProps {
  onChange?: any;
  value: Question;
  isPreview?: boolean;
}

export const QUESTION_TYPES = {
  // SINGLE_CHOICE: 'SC',
  // MULTIPLE_CHOICE_SINGLE_ANSWER: 'MCSA',
  // MULTIPLE_CHOICE_MULTIPLE_ANSWER: 'MCMA',
  OPEN_ENDED: 'OPEN_ENDED',
  OPEN_ENDED_NUMBER: 'OPEN_ENDED_NUMBER',
  REORDER: 'REORDER',
  IMAGE_SELECTION: 'IMAGE_SELECTION',
  TEXT_SELECTION: 'TEXT_SELECTION',
  DATE: 'DATE',
  // YES_NO: 'Y/N',
  // FILL_IN: 'fill_in',
  // REORDER: 'reorder',
  // PAIRING: 'pairing',
  // DROPPING: 'dropping',
};

export const QUESTION_SELECTION_TYPES = [
  QUESTION_TYPES.IMAGE_SELECTION,
  QUESTION_TYPES.TEXT_SELECTION,
];

export const CALCULATION_QUESTION_GROUP_CODE = {
  QG_LOAN_ABILITY: 'QG_LOAN_ABILITY',
  QG_LOAN_PLAN_CALCULATION: 'QG_LOAN_PLAN_CALCULATION',
  QG_LOAN_CORE: 'QG_LOAN_CORE',
};

export const CALCULATION_QUESTION_CODE = {
  OPEN_ENDED_NUMBER: 'OPEN_ENDED_NUMBER',
  QUESTION_LA_INCOME: 'QUESTION_LA_INCOME',
  QUESTION_LA_COST_PER_MONTH: 'QUESTION_LA_COST_PER_MONTH',
  QUESTION_LA_REAL_INTEREST_RATE: 'QUESTION_LA_REAL_INTEREST_RATE',
  QUESTION_LA_BORROWED_TIME: 'QUESTION_LA_BORROWED_TIME',
  QUESTION_LPC_NAME: 'QUESTION_LPC_NAME',
  QUESTION_LPC_EMAIL: 'QUESTION_LPC_EMAIL',
  QUESTION_LPC_PHONE: 'QUESTION_LPC_PHONE',
  QUESTION_LPC_LOAN_DEMAND: 'QUESTION_LPC_LOAN_DEMAND',
  QUESTION_LPC_LOAN_PLAN: 'QUESTION_LPC_LOAN_PLAN',
  QUESTION_LPC_CREDIT_HISTORY: 'QUESTION_LPC_CREDIT_HISTORY',
  QUESTION_LPC_INCOME: 'QUESTION_LPC_INCOME',
  QUESTION_LPC_ACCUMULATED_ASSETS: 'QUESTION_LPC_ACCUMULATED_ASSETS',
  QUESTION_LPC_REPAYMENT_PERIOD: 'QUESTION_LPC_REPAYMENT_PERIOD',
  QUESTION_LPC_EVALUATE_PLAN: 'QUESTION_LPC_EVALUATE_PLAN',
  QUESTION_LPC_EVALUATE_SOURCE_OF_INCOME: 'QUESTION_LPC_EVALUATE_SOURCE_OF_INCOME',
  QUESTION_LPC_EVALUATE_MORTAGE_TYPE: 'QUESTION_LPC_EVALUATE_MORTAGE_TYPE',
  QUESTION_LPC_EVALUATE_CREDIT_HISTORY: 'QUESTION_LPC_EVALUATE_CREDIT_HISTORY',
  QUESTION_LPC_EVALUATE_BORROWING_AGE_AND_PROPERTY_OWNER_AGE: 'QUESTION_LPC_EVALUATE_BORROWING_AGE_AND_PROPERTY_OWNER_AGE',
};

export const BASE_QUESTION_CODE = {
  QUESTION_LC_INCOME: 'QUESTION_LC_INCOME',
  QUESTION_LC_COST_PER_MONTH: 'QUESTION_LC_COST_PER_MONTH',
  QUESTION_LC_LOAN_DEMAND: 'QUESTION_LC_LOAN_DEMAND',
  QUESTION_LC_EVALUATE_PLAN: 'QUESTION_LC_EVALUATE_PLAN',
  QUESTION_LC_BORROWED_TIME: 'QUESTION_LC_BORROWED_TIME',
  QUESTION_LC_EVALUATE_MORTAGE: 'QUESTION_LC_EVALUATE_MORTAGE',
  QUESTION_LC_TIME_DISBURSE: 'QUESTION_LC_TIME_DISBURSE',
  QUESTION_LC_RATE: 'QUESTION_LC_RATE',
  QUESTION_LC_PROPERTY_VALUATION: 'QUESTION_LC_PROPERTY_VALUATION',
  QUESTION_LC_LOAN_EXPENSE: 'QUESTION_LC_LOAN_EXPENSE',
  QUESTION_LC_OTHER_REQUIREMENTS: 'QUESTION_LC_OTHER_REQUIREMENTS',
  QUESTION_LC_MARITAL_STATUS: 'QUESTION_LC_MARITAL_STATUS',
  QUESTION_LC_SOURCE_INCOME: 'QUESTION_LC_SOURCE_INCOME',
  QUESTION_LC_CREDIT_HISTORY: 'QUESTION_LC_CREDIT_HISTORY',
  QUESTION_LC_BOROWER_AGE: 'QUESTION_LC_BOROWER_AGE',
  QUESTION_LC_PROPERTY_OWNER_AGE: 'QUESTION_LC_PROPERTY_OWNER_AGE',
  QUESTION_LC_LOAN_RELATIONSHIP: 'QUESTION_LC_LOAN_RELATIONSHIP',
  QUESTION_LC_ACCUMULATED_ASETS: 'QUESTION_LC_ACCUMULATED_ASETS',
  QUESTION_LC_HISTORY: '000000047',
  QUESTION_LC_CUSTOMER_OUTSTANDING: '000000048',
  LIST_BANK_SUPPORT: 'LIST_BANK_SUPPORT',
  INFO_LC_INCOME: 'INFO_LC_INCOME',
};

export const DISPLAY_NEXT_PREVIEW_QUESTION_BUTTON_TYPES = [QUESTION_TYPES.OPEN_ENDED, QUESTION_TYPES.OPEN_ENDED_NUMBER];
