import { RESPONSE_STATUS_SEEN_BY_FINA_STAFF } from 'constants/crm/task';

export const STATUS_RESPONSE_PARTNER = {
  RECEIVED: RESPONSE_STATUS_SEEN_BY_FINA_STAFF.RECEIVED,
  REJECT: RESPONSE_STATUS_SEEN_BY_FINA_STAFF.REJECT,
  NO_RESPONSE: 'no_response',
  ALL: 'all',
};
