import React from 'react';
import {
  ApartmentOutlined,
  GroupOutlined,
  CodepenOutlined,
  BlockOutlined,
  InsertRowBelowOutlined,
  WindowsOutlined,
  CopyOutlined,
  AuditOutlined,
  PhoneOutlined,
  UserOutlined,
  DollarOutlined,
  SettingOutlined,
  QuestionCircleOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  PictureOutlined,
  WhatsAppOutlined,
  ContactsOutlined,
  UserAddOutlined,
  UsergroupAddOutlined,
  SolutionOutlined,
  ReconciliationOutlined,
  UserSwitchOutlined,
  CloseSquareOutlined,
  MenuUnfoldOutlined,
  HddOutlined,
  FileProtectOutlined,
  HeartOutlined, MedicineBoxOutlined, CodeSandboxOutlined, PullRequestOutlined, BookOutlined, MailOutlined,
} from '@ant-design/icons';
import { TFunction } from 'next-i18next';

export const BusinessMenu = (t: TFunction) => {
  return [
    {
      label: t('Dashboard'),
      icon: <InsertRowBelowOutlined/>,
      href: '/admin/dashboard',
    },
    {
      label: t('Call logs'),
      icon: <PhoneOutlined />,
      href: '/admin/call-logs',
      permissions: ['V_CALL'],
    },
    {
      label: t('Task Management'),
      icon: <ApartmentOutlined/>,
      href: '/admin/tasks',
      defaultOpen: true,
      permissions: ['V_MDT_TASK', 'V_TASK'],
      subMenu: [
        {
          label: 'Yêu cầu chờ tiếp nhận',
          icon: <MenuUnfoldOutlined />,
          href: '/admin/tasks/order',
          permissions: [
            'V_MDT_TASK',
            'V_TASK_COUNSELLING',
            'V_TASK_INTRODUCE_BUYER',
            'V_TASK_WANT_TO_BUY',
            'V_TASK_BOND',
            'V_TASK_FUND',
          ],
        },
        {
          label: t('Counselling request'),
          icon: <MenuUnfoldOutlined />,
          href: '/admin/tasks/task',
          // checkAllPermissions: true,
          permissions: [
            'V_MDT_TASK',
            'V_TASK_COUNSELLING',
            'V_TASK_INTRODUCE_BUYER',
            'V_TASK_WANT_TO_BUY',
            'V_TASK_BOND',
            'V_TASK_FUND',
          ],
        },  
        {
          label: t('Yêu cầu bất động sản'),
          icon: <MenuUnfoldOutlined />,
          href: '/admin/tasks/real-estate',
          permissions: ['V_TASK_REAL_ESTATE'],
        },
        {
          label: t('Cuộc gọi'),
          icon: <PhoneOutlined />,
          href: '/admin/tasks/call',
          permissions: ['V_TASK_CALL'],
        },
        {
          label: t('Xử lý hồ sơ'),
          icon: <MenuUnfoldOutlined />,
          href: '/admin/tasks/deal-processing',
          permissions: ['V_TASK_DEAL_PROCESSING_TASK'],
        },
        {
          label: t('Reason close'),
          icon: <CloseSquareOutlined />,
          href: '/admin/tasks/reason-close',
          permissions: ['V_REASONCLOSETASK', 'V_MDT_REASONCLOSETASK'],
        },
        {
          label: t('requestBackStatusOfTask'),
          icon: <PullRequestOutlined />,
          href: '/admin/tasks/request-back-status',
          permissions: ['V_REQUESTBACKTASKSTATUS', 'V_MDT_REQUESTBACKTASKSTATUS'],
        },
        {
          label: t('configAutoAssignTask'),
          icon: <PullRequestOutlined />,
          href: '/admin/tasks/config-auto-assign-task',
          permissions: ['V_CONFIG_AUTO_ASSIGN_TASK'],
        },
      ],
    },
    {
      label: t('Deals'),
      icon: <AuditOutlined/>,
      href: '/admin/deals',
      defaultOpen: true,
      permissions: ['LOAN_MANAGEMENT'],
      subMenu: [
        {
          label: t('deals.loan'),
          icon: <CodepenOutlined/>,
          href: '/admin/deals/loans',
          permissions: ['V_DEAL', 'LOAN_MANAGEMENT', 'V_MDT_DEAL'],
        },
        {
          label: t('Đối soát giải ngân'),
          icon: <CodepenOutlined/>,
          href: '/admin/deals/for-control-disbursement',
          permissions: ['V_MDT_TRANSACTIONDETAIL'],
        },
        {
          label: t('deal.bonds'),
          icon: <CodepenOutlined/>,
          href: '/admin/deals/bonds',
          permissions: ['V_MDT_TRANSACTION'],
        },
      ],
    },
    {
      label: t('Insurance'),
      icon: <FileProtectOutlined />,
      href: '/admin/insurance',
      defaultOpen: true,
      permissions: ['LOAN_MANAGEMENT'],
      subMenu: [
        {
          label: t('Guarantee Hospital'),
          icon: <MedicineBoxOutlined />,
          href: '/admin/insurance/guarantee-hospital',
          permissions: ['V_ORGANIZATION_PRODUCT'],
        },
        {
          label: t('deals.insurances'),
          icon: <HeartOutlined />,
          href: '/admin/insurance/health-insurance',
          permissions: ['V_DEAL', 'V_MDT_DEAL'],
        },
        {
          label: t('claimInsurance'),
          icon: <WindowsOutlined />,
          href: '/admin/insurance/task',
          permissions: ['V_TASK', 'V_MDT_TASK'],
        },
        {
          label: t('DealClaimInsurance'),
          icon: <FileTextOutlined />,
          href: '/admin/insurance/deal-claim',
          permissions: ['V_DEAL', 'V_MDT_DEAL'],
        },
        {
          label: t('insuranceTransaction'),
          icon: <CodepenOutlined/>,
          href: '/admin/deals/insurances',
        },
      ],
    },
    {
      label: t('Report'),
      icon: <HddOutlined />,
      href: '/admin/reports',
      defaultOpen: true,
      permissions: ['V_STRINGEELOGS'],
      subMenu: [
        {
          label: t('Báo cáo cuộc gọi'),
          icon: <FileTextOutlined />,
          href: '/admin/reports/call-logs',
          permissions: ['V_STRINGEELOGS'],
        },
        {
          label: t('Báo cáo YCTV'),
          icon: <FileTextOutlined />,
          href: '/admin/reports/tasks',
          permissions: ['V_TASK'],
        },
        {
          label: t('Báo cáo HSV'),
          icon: <FileTextOutlined />,
          href: '/admin/reports/deals',
          permissions: ['V_DEAL'],
        },
        {
          label: t('Báo cáo Performance '),
          icon: <FileTextOutlined />,
          href: '/admin/reports/performance',
          permissions: ['ADMIN'],
        },
      ],
    },
    {
      label: t('Products'),
      icon: <WindowsOutlined/>,
      href: '/admin/products',
      defaultOpen: true,
      permissions: ['V_PRODUCT'],
      subMenu: [
        {
          label: t('products.categories'),
          icon: <GroupOutlined/>,
          href: '/admin/products/categories',
          permissions: ['V_CATEGORY', 'V_MDT_CATEGORY'],
        },
        {
          label: t('products.loan'),
          icon: <CodepenOutlined/>,
          href: '/admin/products/loans',
          permissions: ['V_PRODUCT', 'V_MDT_PRODUCT', 'C_PRODUCT'],
        },
        {
          label: t('Products Detail'),
          icon: <CodeSandboxOutlined />,
          href: '/admin/products/product-detail',
          permissions: ['V_PRODUCTDETAIL', 'U_PRODUCTDETAIL'],
        },
        {
          label: t('products.insurance'),
          icon: <BlockOutlined/>,
          href: '/admin/products/insurances',
        },
        {
          label: t('product.bonds'),
          icon: <CodepenOutlined/>,
          href: '/admin/products/bonds',
          permissions: ['V_PRODUCT', 'V_MDT_PRODUCT'],
        },
        {
          label: t('product.fund'),
          icon: <CodepenOutlined/>,
          href: '/admin/products/fund',
          permissions: ['V_PRODUCT', 'V_MDT_PRODUCT'],
        },
        {
          label: t('RE Projects'),
          icon: <BlockOutlined/>,
          href: '/admin/projects',
        },
        {
          label: t('products.properties'),
          icon: <BlockOutlined/>,
          href: '/admin/products/properties',
          permissions: ['V_PROPERTY', 'V_MDT_PROPERTY'],
        },
      ],
    },
    {
      label: t('invest'),
      icon: <WindowsOutlined/>,
      href: '/admin/invest',
      defaultOpen: true,
      permissions: ['V_MDT_TRANSACTION', 'FUND_AGENT'],
      subMenu: [
        {
          label: t('bonds'),
          icon: <GroupOutlined/>,
          href: '/admin/invest/bonds',
          permissions: ['V_MDT_TRANSACTION'],
        },
        {
          label: t('transactionOfFund'),
          icon: <BookOutlined />,
          href: '/admin/invest/transaction-funds',
          permissions: ['FUND_AGENT'],
        },
        {
          label: t('fundTransactionByReferral'),
          icon: <BookOutlined />,
          href: '/admin/invest/fund-trading-by-referral',
          permissions: ['V_MDT_TRANSACTION'],
        },
      ],
    },
    {
      label: t('Transaction'),
      icon: <UserOutlined/>,
      href: '/admin/transaction',
      permissions: ['VIEW_MY_TRANSACTION'],
    },
    {
      label: t('seoLandingPage'),
      icon: <UserOutlined/>,
      href: '/admin/seo-landing-page',
      permissions: ['V_SEOLANDINGPAGE'],
    },
    {
      label: t('users.customers'),
      icon: <UserOutlined/>,
      href: '/admin/fina-staff',
      defaultOpen: true,
      permissions: [
        'VIEW_COLLABORATOR_MENU', 
        'V_MDT_REQUESTACCESSUSER', 
        'V_MDT_USER', 
        'V_USER',
      ],
      subMenu: [
        {
          label: t('customer.search'),
          icon: <CodepenOutlined/>,
          href: '/admin/fina-staff/customers/search',
          permissions: ['V_MDT_REQUESTACCESSUSER'],
        },
        {
          label: t('customer.list'),
          icon: <CodepenOutlined/>,
          href: '/admin/fina-staff/customers',
          permissions: ['V_MDT_USER'],
        },
        {
          label: t('collaborators.list'),
          icon: <CodepenOutlined/>,
          href: '/admin/fina-staff/customers/collaborators',
          permissions: ['VIEW_COLLABORATOR_MENU'],
        },
        {
          label: t('customer.set_permission'),
          icon: <CodepenOutlined/>,
          href: '/admin/fina-staff/customers/access-permission-user',
          permissions: ['V_MDT_REQUESTACCESSUSER'],
        },
        {
          label: t('customer.sharingUser'),
          icon: <CodepenOutlined/>,
          href: '/admin/fina-staff/customers/sharing-view',
          permissions: ['V_MDT_USER', 'V_USER'],
        },
      ],
    },
    {
      label: t('Contact'),
      icon: <WhatsAppOutlined />,
      href: '/admin/business',
      defaultOpen: true,
      permissions: ['V_MDT_CONTACT'],
      subMenu: [
        {
          label: t('Contact'),
          icon: <ContactsOutlined />,
          href: '/admin/business/contacts',
          permissions: ['V_MDT_CONTACT'],
        },
        {
          label: t('Import contact'),
          icon: <UserAddOutlined />,
          href: '/admin/business/import-contact',
        },
      ],
    },
    {
      label: t('Product progress'),
      icon: <BlockOutlined/>,
      href: '/admin/progress-template',
      permissions: ['V_PROGRESSTEMPLATE'],
    },
    {
      label: t('Hoa hồng'),
      icon: <DollarOutlined />,
      href: '/admin/commission',
      defaultOpen: true,
      permissions: ['V_COMMISSION, V_MDT_COMMISSION'],
      subMenu: [
        {
          label: t('Cài đặt hoa hồng tín dụng'),
          icon: <SettingOutlined />,
          href: '/admin/commission/loan-product-settings',
          permissions: ['ADMIN', 'SUPER_ADMIN'],
        },
        {
          label: t('Cài đặt hoa hồng bảo hiểm'),
          icon: <SettingOutlined />,
          href: '/admin/commission/insurance-product-settings',
          permissions: ['ADMIN', 'SUPER_ADMIN'],
        },
        {
          label: t('Hoa hồng FINA nhận'),
          icon: <DollarOutlined />,
          href: '/admin/commission/receive-management',
          permissions: ['ADMIN', 'SUPER_ADMIN'],
        },
        {
          label: t('Hoa hồng FINA trả'),
          icon: <DollarOutlined />,
          href: '/admin/commission/spend-management',
          permissions: ['ADMIN', 'SUPER_ADMIN'],
        },
        {
          label: t('Hoa hồng của tôi'),
          icon: <DollarOutlined />,
          href: '/admin/commission/personal-management',
        },
      ],
    },
    {
      label: t('Documents'),
      icon: <CopyOutlined/>,
      href: '/admin/documents',
      defaultOpen: true,
      permissions: ['V_DOCUMENT', 'V_DOCUMENTCATEGORY', 'V_DOCUMENTTEMPLATE', 'V_MDT_DOCUMENT', 'V_MDT_DOCUMENTCATEGORY', 'V_MDT_DOCUMENTTEMPLATE'],
      subMenu: [
        {
          label: t('documents.categories'),
          icon: <GroupOutlined/>,
          href: '/admin/documents/category',
          permissions: ['V_DOCUMENTCATEGORY'],
        },
        {
          label: t('documents.documents'),
          icon: <CodepenOutlined/>,
          href: '/admin/documents/management',
          permissions: ['V_DOCUMENT'],
        },
        {
          label: t('documents.templates'),
          icon: <BlockOutlined/>,
          href: '/admin/documents/templates',
          permissions: ['V_DOCUMENTTEMPLATE'],
        },
      ],
    },
    {
      label: t('Question groups'),
      icon: <QuestionCircleOutlined/>,
      href: '/admin/question-groups',
      permissions: ['V_QUESTIONGROUP'],
    },
    {
      label: t('Config question groups'),
      icon: <QuestionCircleOutlined/>,
      href: '/admin/config-question-groups',
      permissions: ['V_CONFIGVALUE'],
    },
    {
      label: t('Client reviews'),
      icon: <FileSearchOutlined />,
      href: '/admin/client-reviews',
      permissions: ['ADMIN', 'SUPER_ADMIN'],
    },
    {
      label: 'Bảng lãi suất',
      icon: <FileSearchOutlined />,
      href: '/admin/preferential-reviews',
      permissions: ['ADMIN', 'SUPER_ADMIN'],
    },
    {
      label: t('Bannners'),
      icon: <PictureOutlined />,
      href: '/admin/banners',
      permissions: ['V_BANNER'],
    },
    {
      label: t('recruit.recruit'),
      icon: <UsergroupAddOutlined />,
      href: '/admin/recruit',
      defaultOpen: true,
      permissions: ['V_JOB', 'V_CURRICULUMVITAE', 'V_CONTACTUS'],
      subMenu: [
        {
          label: t('recruit.jobs'),
          icon: <ReconciliationOutlined />,
          href: '/admin/recruit/jobs',
          permissions: ['V_JOB'],
        },
        {
          label: t('recruit.cv'),
          icon: <SolutionOutlined />,
          href: '/admin/recruit/cv',
          permissions: ['V_CURRICULUMVITAE'],
        },
        {
          label: t('recruit.contact-us'),
          icon: <UserSwitchOutlined />,
          href: '/admin/recruit/contact-us',
          permissions: ['V_CONTACTUS'],
        },
      ],
    },
    {
      label: t('Send Email Auto', { vn: 'Send Email Auto' }),
      icon: <MailOutlined />,
      permissions: ['ADMIN'],
      href: '/admin/send-email-fina',
    },
    {
      label: t('News'),
      icon: <FileTextOutlined />,
      href: '/admin/news-management',
      defaultOpen: true,
      permissions: ['V_NEWS', 'V_CATEGORY'],
      subMenu: [
        {
          label: t('News category'),
          icon: <FileTextOutlined />,
          href: '/admin/news-management/category',
          permissions: ['V_CATEGORY'],
        },
        {
          label: t('News'),
          icon: <FileTextOutlined />,
          href: '/admin/news-management/news',
          permissions: ['V_NEWS'],
        },
      ],
    },
    {
      label: t('Promotions'),
      href: '/admin/promotions',
      defaultOpen: true,
      permissions: ['ADMIN', 'SUPER_ADMIN'],
      subMenu: [
        {
          label: t('Promotions result'),
          icon: <PictureOutlined />,
          href: '/admin/promotions/alma-registrations',
          permissions: ['ADMIN', 'SUPER_ADMIN'],
        },
      ],
    },
    {
      label: t('Statuses'),
      icon: <ApartmentOutlined/>,
      href: '/admin/statuses',
      permissions: ['V_STATUS', 'V_MDT_STATUS'],
    },
  ];
};
