export enum EVENT_MESSAGE_WORKFLOW_STATUS {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
  PROCESSING = 'processing',
  DONE = 'done',
  ERROR = 'error',
}

export const EVENT_MESSAGE_WORKFLOW_STATUS_LABEL_MAPPING = {
  [EVENT_MESSAGE_WORKFLOW_STATUS.ACTIVE]: 'Active',
  [EVENT_MESSAGE_WORKFLOW_STATUS.INACTIVE]: 'Inactive',
  [EVENT_MESSAGE_WORKFLOW_STATUS.PROCESSING]: 'Processing',
  [EVENT_MESSAGE_WORKFLOW_STATUS.DONE]: 'Sent',
  [EVENT_MESSAGE_WORKFLOW_STATUS.ERROR]: 'Error',
};
