export const DEFAULT_BORROWED_TIME = 20; // year
export const DEFAULT_DTI_INDEX = 80; // percentage

export const DEFAULT_REAL_INTEREST_RATE_FIRST = 10; // percentage
export const DEFAULT_REAL_INTEREST_RATE_SECOND = 11; // percentage
export const DEFAULT_REAL_INTEREST_RATE_THIRD = 12; // percentage

export const DEFAULT_REAL_INTEREST_RATES = [DEFAULT_REAL_INTEREST_RATE_FIRST, DEFAULT_REAL_INTEREST_RATE_SECOND, DEFAULT_REAL_INTEREST_RATE_THIRD];
export const DEFAULT_BORROWED_TIMES = [DEFAULT_BORROWED_TIME - 5, DEFAULT_BORROWED_TIME, DEFAULT_BORROWED_TIME + 5];
